### ISSUE TITLE
[16.0] Update to `transfer_field_to_modifiers` in Odoo Core

### ISSUE THREAD

**Issue by vincentius** [OCA/brand#142]
Odoo changed the method signature for `transfer_field_to_modifiers` on the model `ir.ui.view` in this commit: https://github.com/odoo/odoo/commit/5a68d254949f1d0ff545023cfd14890efff10f5f

## Module
`brand`

## Describe the bug
A traceback appears we try to open the `tree` or `form` view of a model that's mixed in with `res.brand.mixin`.

## To Reproduce
**Affected versions**: 16.0

1. open the `tree` or `form` view of a model that's mixed in with `res.brand.mixin`.

**Comment by bealdav** [comment]
@vincentius now fixed ? Issue to close ?
