### ISSUE TITLE
[15.0] [16.0] "web.report_assets_common" defined for non-existing file in brand_external_report_layout

### ISSUE THREAD

**Issue by TadeuszKarpinski** [OCA/brand#146]
## Module
brand_external_report_layout

## Describe the bug
in __manifest__.py of brand_external_report_layout assets is defnied

`
    "assets": {
        "web.report_assets_common": [
            "/brand_external_report_layout/"
            "static/src/legacy/scss/asset_styles_brand_report.scss"
        ]
    },
`
but this file doesn't exist. While previewing report error about missing file is shown

## To Reproduce
15.0, 16.0

1. Install module
2. Open settings -> User & Companies -> Brands
3. Create new brand
4. Click Change Document Template

![image](https://user-images.githubusercontent.com/23718660/208900660-384c266e-be1d-4c2b-b765-7c4687c4b5b9.png)

**Comment by sbejaoui** [comment]
The file is created as attachment at module install, try to re-install the module

https://github.com/OCA/brand/blob/948f756f81ce5f600d517e1ea089d324231d99fc/brand_external_report_layout/views/report_template.xml#L234-L242

![image](https://user-images.githubusercontent.com/12665409/208924686-73b70c97-5e24-40ec-b32a-878b42738069.png)
