### ISSUE TITLE
Brand missing on create account.move

### ISSUE THREAD

**Issue by TimGlimmerveen-360ERP** [OCA/brand#163]
## Module
account_brand 
## Describe the bug
During the creation of an invoice brand_id is not visible in the form view.
## To Reproduce
**Affected versions**: 15.0
1. Create new invoice
2. Brand is missing in the form view during the create process

**Expected behavior**
Once a manual invoice is created brand_id should be visible in the form view

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by sbejaoui** [comment]
Hi,

You need to set the brand use level in the settings. The brand field will be visible if the use level is optional or required.

![image](https://github.com/OCA/brand/assets/12665409/e977b69b-bd2c-455f-8f8d-fc14e3e57f27)

![image](https://github.com/OCA/brand/assets/12665409/d0440340-6347-4d40-ac31-cd85cb648bbf)

**Comment by TimGlimmerveen-360ERP** [comment]
Hi @sbejaoui 

Thanks for the quick response.
We've got the setting posted as below. Brand use is required. 
<img width="470" alt="2023-05-24_14h09_00" src="https://github.com/OCA/brand/assets/113090403/08d0a50a-c3f3-40d3-bfdb-5c008763151e">

<img width="622" alt="2023-05-24_14h09_43" src="https://github.com/OCA/brand/assets/113090403/faa429ca-e05e-4cf7-b087-6564c546786b">

**Comment by sbejaoui** [comment]
Sorry, I didn't see it's about version 15.0. I confirm the bug.
