### ISSUE TITLE
Duplicate repo with operating-unit

### ISSUE THREAD

**Issue by FernandoRomera** [OCA/brand#32]
Hello,

I would like to know if this module is very different from operating-unit because in my opinion they do the same and it is duplicating.

Edit: @pedrobaeza

**Comment by sbejaoui** [comment]
Hi,

IMO, there are some similarities, like the fact that a brand and operating unit are sub-entities in a  company. 

But a brand name do not divide the company from a Business/Divisional axis and don't operates as an independent unit (like the description of OU says). 

The use case here, in the same company, salesperson are able to sell products in a different brand name then the company name.

https://github.com/OCA/partner-contact/issues/765, is the discussion that gave life to this repo. Please, take a look for more info.


Regards

**Comment by FernandoRomera** [comment]
Hi,

After reading the conversation, a question has arisen and to better understand the difference I would like to ask the following. Here is the list of modules that operating-unit has compared to the modules in this repository:

- account_operating_unit => account_brand
- agreement_operating_unit => contract_brand
- analytic_operating_unit => analytic_brand [PR]
- crm_operating_unit
- field_service_operating_unit
- hr_contract_operating_unit
- hr_expense_operating_unit
- hr_payroll_operating_unit
- mis_builder_operating_unit
- mrp_operating_unit
- product_operaing_unit
- project_operating_unit
- purchase_operating_unit
- purchase_request_operating_unit
- res_partner_operating_unit => res_partner_brand [PR]
- sales_team_operating_unit
- stock_account_operating_unit
- stock_operating_unit => stock_brand [PR]
- sale_operating_unit => sale_brand
- sale_stock_operating_unit

Of those who only have an operating-unit, do you plan to add one to this repo?
