### ISSUE TITLE
Resume: OCA/brand Manage brands for product and companies

### ISSUE THREAD

**Issue by rafaelbn** [OCA/brand#4]
Hi 

This is a resume

Read: https://github.com/OCA/partner-contact/issues/765

I'm new in this repository but not in working with brands. I create this issue as introduction of what's is done around brands:

### Related to Partners
**Scenario 1**: My company or companies (res.company) sell diferent company's brands (my brands). Example: Danone, Dadone's companies have brands like Danone, Danette, Actimel, Danonino, Activia, Oikos, ....

- [x] Partner Brand: relate / add brand to res.partners (module [partner_brand](https://github.com/OCA/brand/pull/1)) `12`
- [x] Sale Brand: This module allows you to send branded quotations and sales orders to your
customers (module [sale_brand](https://github.com/OCA/brand/pull/3)) `12`
- [x] Account Brand:  This module allows you to send branded invoices to your customers. It adds a brand field on the invoice and the brand information to the PDF
report (module [account_brand](https://github.com/OCA/brand/pull/2)) `12`

Note: In Spanish Localization we are using Brand (commercial Brand) since OpenERP 5: https://github.com/OCA/l10n-spain/blame/12.0/l10n_es_partner/README.rst#L30 :
* Add the field * Commercial name * to the companies and search for it.
* Allows you to define a pattern of the name to display from the name and the
   business name of the company.

### Related to Products
**Scenario 2**: My company or companies product of different brands. Example: Lidl. Lidl sale product of diferent brands: Nestle, Cocacola, Danone, Heinz, ....

- Product Brand: relate / add brand to products (module [product_brand](https://github.com/OCA/product-attribute/tree/12.0/product_brand)) `12.0 / 11.0 / 10.0 / 9.0 / 8.0 / 7.0 / 6.1`

- Website Product Brand: Product Brand Filtering in Website (module [website_sale_product_brand](https://github.com/OCA/e-commerce/tree/11.0/website_sale_product_brand)) `11.0 / 9.0 / 8.0`

- Product Brand Sale Report: Adds product brand to the sale report. ([product_brand_sale_report](https://github.com/OCA/sale-reporting/tree/9.0/product_brand_sale_report)) `9`

- Product Brand in Invoices Analysis: Adds product brand to the invoices analysis report. Module:  [product_brand_invoice_report](https://github.com/OCA/account-invoice-reporting/tree/9.0/product_brand_invoice_report) `9`

**Comment by sbejaoui** [comment]
Hi @rafaelbn ,
I was planning to create an issue that summarize the situation but you were faster.
Well done. Thank you.

I am not sure if the modules related to product_brand should be moved to this repository because what is already done concerns the company brands (a company that sells its products and services under different brands).

The product brand module is almost used to group products by brand and not to show the company brands. So, IMO, it's more of a product attribute.

There is a use case where a company want to split its catalog by its brands. In that case, the company brand and the product brand can be the same.

Unfortunately, the company brand and the product are two different technical objects. If we decide to go for the use case where it's the same, we need to plan an extra work for a migration from one to the other.

**Comment by rafaelbn** [comment]
Hi @sbejaoui ,

So scenarios are:

- My company or companies (res.company) sell diferent company's brands (my brands).

Example: Danone, Dadone's companies have  brands like Danone, Danette, Actimel, Danonino, Activia, Oikos, ....

- My company or companies product of different brands:

Example: Lidl, Lidl sale product of diferent brands: Nestle, Cocacola, Danone, Heinz, ....

Is it?

**Comment by sbejaoui** [comment]
Exactly,

**Comment by sbejaoui** [comment]
> Hi @sbejaoui ,
> 
> So scenarios are:
> 
> * My company or companies (res.company) sell diferent company's brands (my brands).
> 
> Example: Danone, Dadone's companies have brands like Danone, Danette, Actimel, Danonino, Activia, Oikos, ....
> 
> * My company or companies product of different brands:
> 
> Example: Lidl, Lidl sale product of diferent brands: Nestle, Cocacola, Danone, Heinz, ....
> 
> Is it?

Exactly,

**Comment by AntoniRomera** [comment]
Hi @sbejaoui,

Can records be filtered by brand, that is, will a seller only have access to their allowed brands? Or is this scenario not covered?

Edit: 

Hello,

Seeing that my comment has not generated any response, I have a project in hand where I see that the modules in this repository are as indicated, but my client needs to be able to indicate to users the brands with which he is allowed to work. Is this scenario raised?

An example,

A company sells Brand_A and Brand_B, they have a vendor by brand and they can only see the records of the brand they work with

@sbejaoui 

@pedrobaeza At some point, this scenario was discussed?
