### ISSUE TITLE
Brand for e-commerce website

### ISSUE THREAD

**Issue by abyte20** [OCA/brand#60]
Hello,
This development is really useful, I am grateful.
If I create a sales invoice and select brand, the invoice is generated with the new brand information, and this is great.

But I do not know how to make the sales invoices of the website (e-commerce) have the template of the brand.
If I try to edit the website sales orders, brand is not an editable field, as it is in the billing module.
Thanks
![Captura de pantalla de 2021-01-06 01-49-26](https://user-images.githubusercontent.com/74670012/103715648-7844f680-4fc1-11eb-8a82-e65463990bbd.png)

**Comment by sbejaoui** [comment]
[sale_brand](https://github.com/OCA/brand/tree/13.0/sale_brand) module add the brand to the sale order level

**Comment by abyte20** [comment]
Hello,
Yes, work on sales quotation, but don't work on e-commerce orders. is this right?

**Comment by sbejaoui** [comment]
You need to find a way how to set the brand on sale orders created from e-shop.

- you can add a field to the eshop page
- or add default value in the sale order

**Comment by abyte20** [comment]
I don't know how to do this.
Can be it done in the backend or in the source code?
I know a bit about Python programming and I'm starting to get to know Odoo, but I'm still a newbie...
