### ISSUE TITLE
e-commerce error:  Brand is required

### ISSUE THREAD

**Issue by abyte20** [OCA/brand#61]
Hi,
If I go to Settings > General Settings and select the brand use level "Required" I can't buy in my e-shop.
When we add a product to the cart this show:

Error: Brand is required

Thanks

**Comment by pedrobaeza** [comment]
There's no support yet to e-commerce for brands. You need to develop a website_sale_brand module.

**Comment by abyte20** [comment]
aaa, ok. 
I will try to develop it.
But it's my first time, any links?

**Comment by pedrobaeza** [comment]
Well, you have to check other existing modules to try to mimic then. One similar is https://github.com/OCA/e-commerce/tree/12.0/website_sale_order_type
