### ISSUE TITLE
Brand not working with POS - Enhancement

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/brand#67]
If you use Brand, you cannot close and validate Pos.

A new module is needed to solve this

**Comment by sbejaoui** [comment]
do you get an error message?

**Comment by fgarcia-humanoide** [comment]
yes, it sais that brand is not defined. it is a message , not an error.

**Comment by fgarcia-humanoide** [comment]
i will send screenshot later

thanks

**Comment by fgarcia-humanoide** [comment]
![Capturabrand](https://user-images.githubusercontent.com/7599709/119357206-9462df00-bca7-11eb-869a-6af758ad3d98.JPG)
