### ISSUE TITLE
No branding on sales documents

### ISSUE THREAD

**Issue by th3penguinwhisperer** [OCA/brand#68]
Odoo 13.0-20210518 (Community Edition) 
Brand modules are installed from git on the 13.0 release.
Running Odoo in Docker.

I configured 2 brands. I can select a brand on the Quotation, ... however when I print I see no branded info. Just the general company information that's configured. Same for when I go to preview I see the normal company info and not the branded info.

Nothing else is really configured. This was a fresh install. Can someone confirm this (doesn't) work (anymore)?

Thanks!

**Comment by sbejaoui** [comment]
Hi,

you need to install [brand_external_report_layout](https://github.com/OCA/brand/tree/13.0/brand_external_report_layout).

Regards,

**Comment by th3penguinwhisperer** [comment]
Thanks for the quick response. It's much appreciated. Perhaps this dependency could be added? Or is there a need to have the sale_brand, ... without the brand_external_report_layout addon?

There's not that much documentation and I don't think I've found this mentioned.

I did had to reopen my brands and save them again and after that the documents are generated with their respective brands.

:+1:

**Comment by sbejaoui** [comment]
For some use cases, we would have the brand for reporting purpose without branding the documents. So, it's better to keep it like this.

**Comment by th3penguinwhisperer** [comment]
Ok. But it would be good that the need for this addon when you want branded documents is mentioned in the Readme. The docs mention creating the brand and after that you can generate the documents with the respective brand and so it seems like having the reporting module is the expected "default" behavior.

**Comment by sbejaoui** [comment]
I agree, we need to work on the documentation.
